services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-06-29T01-20-47Z
    command: server --console-address ":9001" /data
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio-data:/data
